name: Dash DocSet - AWS CloudFormation Template Reference

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install Dependencies
      run: yarn

    - name: Fix jq
      working-directory: ${{ github.workspace }}
      run: |
        pwd
        ls -l
        ls -l node_modules/
        file ./node_modules/node-jq/bin/jq
        rm ./node_modules/node-jq/bin/jq && ln -s $(brew --prefix jq)/bin/jq ./node_modules/node-jq/bin/jq

    - name: Build DocSet
      run: |
        npm run build
        npm package
    
    - name: Archive DocSet Artifact
      uses: actions/upload-artifact@v1
      with:
        name: AWS_CloudFormation_Template_Reference
        path: AWS_CloudFormation_Template_Reference.tgz
